### ISSUE TITLE
IPI

### ISSUE THREAD

**Issue by JasonWap** [Luo-Yihong/YOSO#3]
Thank you for your nice work!

I have a question about the Informative Prior Initialization (IPI).

In your paper, this term seems to be incorporated into the training step. (as a learnable parameter?)
(Additionally, I just wonder if the positions of the average and variance values ​​have changed in your equation.)

If right, is it applied to the model you shared with diffusers pipeline?
or is it not applied with the inference?

If I understand wrong, could you explain the term in detail? (how we can apply it in practice)

**Comment by Luo-Yihong** [comment]
The IPI is not involved in the training process. And the average and variance would not be changed. 

It is a post-estimation stage. We use multiple samples for estimating the average and variance. 

To use IPI, we only need to initialize the noise with IPI instead of Standard Gaussian Distribution. Other operations in inference do not need to be changed.

If you have further questions, feel free to ask.
